#! /usr/bin/env node

console.log('This script populates topics. Specified database as argument - e.g.: populatedb mongodb://your_username:your_password@your_dabase_url');

//Get arguments passed on command line
var userArgs = process.argv.slice(2);
if (!userArgs[0].startsWith('mongodb://')) {
    console.log('ERROR: You need to specify a valid mongodb URL as the first argument');
    return
}

var async = require('async')
var Topic = require('../models/topicModel')

var mongoose = require('mongoose');
var mongoDB = userArgs[0];
mongoose.connect(mongoDB);
var db = mongoose.connection;
mongoose.connection.on('error', console.error.bind(console, 'MongoDB connection error:'));

var topics = []

function topicCreate(topic_name, cb) {
  topicDetail = {name:topic_name}
  
  var topic = new Topic(topicDetail);
       
  topic.save(function (err) {
    if (err) {
      cb(err, null)
      return
    }
    console.log('New Topic: ' + topic);
    topics.push(topic)
    cb(null, topic)
  }  );
}

function createTopics(cb) {
    async.parallel([
        function(callback) {
          topicCreate('First', callback)
        },
        function(callback) {
          topicCreate('Second', callback)
        }
    ],
        // optional callback
        cb);
}

async.series([
    createTopics
],
// optional callback
function(err, results) {
    if (err) {
        console.log('FINAL ERR: '+err);
    }
    else {
        console.log('Topics: '+topics);
    }
    //All done, disconnect from database
    mongoose.connection.close();
});
